steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--network=cloudbuild'
  - '--no-cache'
  - '--build-arg'
  - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
  - '--build-arg'
  - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
  - '-t'
  - 'asia-northeast1-docker.pkg.dev/aibond-479715/aibond/web:latest'
  - '-t'
  - 'asia-northeast1-docker.pkg.dev/aibond-479715/aibond/web:${SHORT_SHA}'
  - '.'

images:
- 'asia-northeast1-docker.pkg.dev/aibond-479715/aibond/web:latest'
- 'asia-northeast1-docker.pkg.dev/aibond-479715/aibond/web:${SHORT_SHA}'
